/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardJailRouteRouteImport } from './routes/(dashboard)/jail/route'
import { Route as dashboardOrganizationRouteRouteImport } from './routes/(dashboard)/organization/route'
import { Route as dashboardTendersRouteRouteImport } from './routes/(dashboard)/tenders/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as dashboardJailIndexRouteImport } from './routes/(dashboard)/jail/index'
import { Route as dashboardJailCreateNewJailRouteImport } from './routes/(dashboard)/jail/create-new-jail'
import { Route as dashboardJailViewAllJailsRouteImport } from './routes/(dashboard)/jail/view-all-jails'
import { Route as dashboardOrganizationIndexRouteImport } from './routes/(dashboard)/organization/index'
import { Route as dashboardOrganizationCreateNewOrganizationRouteImport } from './routes/(dashboard)/organization/create-new-organization'
import { Route as dashboardOrganizationViewAllOrganizationsRouteImport } from './routes/(dashboard)/organization/view-all-organizations'
import { Route as dashboardTendersIndexRouteImport } from './routes/(dashboard)/tenders/index'
import { Route as dashboardTendersCreateNewTenderRouteImport } from './routes/(dashboard)/tenders/create-new-tender'
import { Route as dashboardTendersViewTendersRouteImport } from './routes/(dashboard)/tenders/view-tenders'
import { Route as dashboardTenderParticipantParticipantIdRouteImport } from './routes/(dashboard)/tender-participant/participant.$id'
import { Route as dashboardTendersTenderDetailsIdRouteImport } from './routes/(dashboard)/tenders/tender-details.$id'
import { Route as dashboardTendersTenderDetailsIdAddParticipantsRouteImport } from './routes/(dashboard)/tenders/tender-details_.$id.add-participants'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardJailRouteRoute = dashboardJailRouteRouteImport.update({
  id: '/jail',
  path: '/jail',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardOrganizationRouteRoute =
  dashboardOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTendersRouteRoute = dashboardTendersRouteRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const dashboardJailIndexRoute = dashboardJailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardJailRouteRoute,
} as any)
const dashboardJailCreateNewJailRoute =
  dashboardJailCreateNewJailRouteImport.update({
    id: '/create-new-jail',
    path: '/create-new-jail',
    getParentRoute: () => dashboardJailRouteRoute,
  } as any)
const dashboardJailViewAllJailsRoute =
  dashboardJailViewAllJailsRouteImport.update({
    id: '/view-all-jails',
    path: '/view-all-jails',
    getParentRoute: () => dashboardJailRouteRoute,
  } as any)
const dashboardOrganizationIndexRoute =
  dashboardOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardOrganizationRouteRoute,
  } as any)
const dashboardOrganizationCreateNewOrganizationRoute =
  dashboardOrganizationCreateNewOrganizationRouteImport.update({
    id: '/create-new-organization',
    path: '/create-new-organization',
    getParentRoute: () => dashboardOrganizationRouteRoute,
  } as any)
const dashboardOrganizationViewAllOrganizationsRoute =
  dashboardOrganizationViewAllOrganizationsRouteImport.update({
    id: '/view-all-organizations',
    path: '/view-all-organizations',
    getParentRoute: () => dashboardOrganizationRouteRoute,
  } as any)
const dashboardTendersIndexRoute = dashboardTendersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardTendersRouteRoute,
} as any)
const dashboardTendersCreateNewTenderRoute =
  dashboardTendersCreateNewTenderRouteImport.update({
    id: '/create-new-tender',
    path: '/create-new-tender',
    getParentRoute: () => dashboardTendersRouteRoute,
  } as any)
const dashboardTendersViewTendersRoute =
  dashboardTendersViewTendersRouteImport.update({
    id: '/view-tenders',
    path: '/view-tenders',
    getParentRoute: () => dashboardTendersRouteRoute,
  } as any)
const dashboardTenderParticipantParticipantIdRoute =
  dashboardTenderParticipantParticipantIdRouteImport.update({
    id: '/tender-participant/participant/$id',
    path: '/tender-participant/participant/$id',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTendersTenderDetailsIdRoute =
  dashboardTendersTenderDetailsIdRouteImport.update({
    id: '/tender-details/$id',
    path: '/tender-details/$id',
    getParentRoute: () => dashboardTendersRouteRoute,
  } as any)
const dashboardTendersTenderDetailsIdAddParticipantsRoute =
  dashboardTendersTenderDetailsIdAddParticipantsRouteImport.update({
    id: '/tender-details_/$id/add-participants',
    path: '/tender-details/$id/add-participants',
    getParentRoute: () => dashboardTendersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/jail': typeof dashboardJailRouteRouteWithChildren
  '/organization': typeof dashboardOrganizationRouteRouteWithChildren
  '/tenders': typeof dashboardTendersRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof dashboardIndexRoute
  '/jail/create-new-jail': typeof dashboardJailCreateNewJailRoute
  '/jail/view-all-jails': typeof dashboardJailViewAllJailsRoute
  '/organization/create-new-organization': typeof dashboardOrganizationCreateNewOrganizationRoute
  '/organization/view-all-organizations': typeof dashboardOrganizationViewAllOrganizationsRoute
  '/tenders/create-new-tender': typeof dashboardTendersCreateNewTenderRoute
  '/tenders/view-tenders': typeof dashboardTendersViewTendersRoute
  '/jail/': typeof dashboardJailIndexRoute
  '/organization/': typeof dashboardOrganizationIndexRoute
  '/tenders/': typeof dashboardTendersIndexRoute
  '/tender-participant/participant/$id': typeof dashboardTenderParticipantParticipantIdRoute
  '/tenders/tender-details/$id': typeof dashboardTendersTenderDetailsIdRoute
  '/tenders/tender-details/$id/add-participants': typeof dashboardTendersTenderDetailsIdAddParticipantsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof dashboardIndexRoute
  '/jail/create-new-jail': typeof dashboardJailCreateNewJailRoute
  '/jail/view-all-jails': typeof dashboardJailViewAllJailsRoute
  '/organization/create-new-organization': typeof dashboardOrganizationCreateNewOrganizationRoute
  '/organization/view-all-organizations': typeof dashboardOrganizationViewAllOrganizationsRoute
  '/tenders/create-new-tender': typeof dashboardTendersCreateNewTenderRoute
  '/tenders/view-tenders': typeof dashboardTendersViewTendersRoute
  '/jail': typeof dashboardJailIndexRoute
  '/organization': typeof dashboardOrganizationIndexRoute
  '/tenders': typeof dashboardTendersIndexRoute
  '/tender-participant/participant/$id': typeof dashboardTenderParticipantParticipantIdRoute
  '/tenders/tender-details/$id': typeof dashboardTendersTenderDetailsIdRoute
  '/tenders/tender-details/$id/add-participants': typeof dashboardTendersTenderDetailsIdAddParticipantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(dashboard)/jail': typeof dashboardJailRouteRouteWithChildren
  '/(dashboard)/organization': typeof dashboardOrganizationRouteRouteWithChildren
  '/(dashboard)/tenders': typeof dashboardTendersRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/jail/create-new-jail': typeof dashboardJailCreateNewJailRoute
  '/(dashboard)/jail/view-all-jails': typeof dashboardJailViewAllJailsRoute
  '/(dashboard)/organization/create-new-organization': typeof dashboardOrganizationCreateNewOrganizationRoute
  '/(dashboard)/organization/view-all-organizations': typeof dashboardOrganizationViewAllOrganizationsRoute
  '/(dashboard)/tenders/create-new-tender': typeof dashboardTendersCreateNewTenderRoute
  '/(dashboard)/tenders/view-tenders': typeof dashboardTendersViewTendersRoute
  '/(dashboard)/jail/': typeof dashboardJailIndexRoute
  '/(dashboard)/organization/': typeof dashboardOrganizationIndexRoute
  '/(dashboard)/tenders/': typeof dashboardTendersIndexRoute
  '/(dashboard)/tender-participant/participant/$id': typeof dashboardTenderParticipantParticipantIdRoute
  '/(dashboard)/tenders/tender-details/$id': typeof dashboardTendersTenderDetailsIdRoute
  '/(dashboard)/tenders/tender-details_/$id/add-participants': typeof dashboardTendersTenderDetailsIdAddParticipantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/jail'
    | '/organization'
    | '/tenders'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/jail/create-new-jail'
    | '/jail/view-all-jails'
    | '/organization/create-new-organization'
    | '/organization/view-all-organizations'
    | '/tenders/create-new-tender'
    | '/tenders/view-tenders'
    | '/jail/'
    | '/organization/'
    | '/tenders/'
    | '/tender-participant/participant/$id'
    | '/tenders/tender-details/$id'
    | '/tenders/tender-details/$id/add-participants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/jail/create-new-jail'
    | '/jail/view-all-jails'
    | '/organization/create-new-organization'
    | '/organization/view-all-organizations'
    | '/tenders/create-new-tender'
    | '/tenders/view-tenders'
    | '/jail'
    | '/organization'
    | '/tenders'
    | '/tender-participant/participant/$id'
    | '/tenders/tender-details/$id'
    | '/tenders/tender-details/$id/add-participants'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/auth'
    | '/(dashboard)/jail'
    | '/(dashboard)/organization'
    | '/(dashboard)/tenders'
    | '/auth/login'
    | '/auth/signup'
    | '/(dashboard)/'
    | '/(dashboard)/jail/create-new-jail'
    | '/(dashboard)/jail/view-all-jails'
    | '/(dashboard)/organization/create-new-organization'
    | '/(dashboard)/organization/view-all-organizations'
    | '/(dashboard)/tenders/create-new-tender'
    | '/(dashboard)/tenders/view-tenders'
    | '/(dashboard)/jail/'
    | '/(dashboard)/organization/'
    | '/(dashboard)/tenders/'
    | '/(dashboard)/tender-participant/participant/$id'
    | '/(dashboard)/tenders/tender-details/$id'
    | '/(dashboard)/tenders/tender-details_/$id/add-participants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/jail': {
      id: '/(dashboard)/jail'
      path: '/jail'
      fullPath: '/jail'
      preLoaderRoute: typeof dashboardJailRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/organization': {
      id: '/(dashboard)/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof dashboardOrganizationRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/tenders': {
      id: '/(dashboard)/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof dashboardTendersRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(dashboard)/jail/': {
      id: '/(dashboard)/jail/'
      path: '/'
      fullPath: '/jail/'
      preLoaderRoute: typeof dashboardJailIndexRouteImport
      parentRoute: typeof dashboardJailRouteRoute
    }
    '/(dashboard)/jail/create-new-jail': {
      id: '/(dashboard)/jail/create-new-jail'
      path: '/create-new-jail'
      fullPath: '/jail/create-new-jail'
      preLoaderRoute: typeof dashboardJailCreateNewJailRouteImport
      parentRoute: typeof dashboardJailRouteRoute
    }
    '/(dashboard)/jail/view-all-jails': {
      id: '/(dashboard)/jail/view-all-jails'
      path: '/view-all-jails'
      fullPath: '/jail/view-all-jails'
      preLoaderRoute: typeof dashboardJailViewAllJailsRouteImport
      parentRoute: typeof dashboardJailRouteRoute
    }
    '/(dashboard)/organization/': {
      id: '/(dashboard)/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof dashboardOrganizationIndexRouteImport
      parentRoute: typeof dashboardOrganizationRouteRoute
    }
    '/(dashboard)/organization/create-new-organization': {
      id: '/(dashboard)/organization/create-new-organization'
      path: '/create-new-organization'
      fullPath: '/organization/create-new-organization'
      preLoaderRoute: typeof dashboardOrganizationCreateNewOrganizationRouteImport
      parentRoute: typeof dashboardOrganizationRouteRoute
    }
    '/(dashboard)/organization/view-all-organizations': {
      id: '/(dashboard)/organization/view-all-organizations'
      path: '/view-all-organizations'
      fullPath: '/organization/view-all-organizations'
      preLoaderRoute: typeof dashboardOrganizationViewAllOrganizationsRouteImport
      parentRoute: typeof dashboardOrganizationRouteRoute
    }
    '/(dashboard)/tenders/': {
      id: '/(dashboard)/tenders/'
      path: '/'
      fullPath: '/tenders/'
      preLoaderRoute: typeof dashboardTendersIndexRouteImport
      parentRoute: typeof dashboardTendersRouteRoute
    }
    '/(dashboard)/tenders/create-new-tender': {
      id: '/(dashboard)/tenders/create-new-tender'
      path: '/create-new-tender'
      fullPath: '/tenders/create-new-tender'
      preLoaderRoute: typeof dashboardTendersCreateNewTenderRouteImport
      parentRoute: typeof dashboardTendersRouteRoute
    }
    '/(dashboard)/tenders/view-tenders': {
      id: '/(dashboard)/tenders/view-tenders'
      path: '/view-tenders'
      fullPath: '/tenders/view-tenders'
      preLoaderRoute: typeof dashboardTendersViewTendersRouteImport
      parentRoute: typeof dashboardTendersRouteRoute
    }
    '/(dashboard)/tender-participant/participant/$id': {
      id: '/(dashboard)/tender-participant/participant/$id'
      path: '/tender-participant/participant/$id'
      fullPath: '/tender-participant/participant/$id'
      preLoaderRoute: typeof dashboardTenderParticipantParticipantIdRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/tenders/tender-details/$id': {
      id: '/(dashboard)/tenders/tender-details/$id'
      path: '/tender-details/$id'
      fullPath: '/tenders/tender-details/$id'
      preLoaderRoute: typeof dashboardTendersTenderDetailsIdRouteImport
      parentRoute: typeof dashboardTendersRouteRoute
    }
    '/(dashboard)/tenders/tender-details_/$id/add-participants': {
      id: '/(dashboard)/tenders/tender-details_/$id/add-participants'
      path: '/tender-details/$id/add-participants'
      fullPath: '/tenders/tender-details/$id/add-participants'
      preLoaderRoute: typeof dashboardTendersTenderDetailsIdAddParticipantsRouteImport
      parentRoute: typeof dashboardTendersRouteRoute
    }
  }
}

interface dashboardJailRouteRouteChildren {
  dashboardJailCreateNewJailRoute: typeof dashboardJailCreateNewJailRoute
  dashboardJailViewAllJailsRoute: typeof dashboardJailViewAllJailsRoute
  dashboardJailIndexRoute: typeof dashboardJailIndexRoute
}

const dashboardJailRouteRouteChildren: dashboardJailRouteRouteChildren = {
  dashboardJailCreateNewJailRoute: dashboardJailCreateNewJailRoute,
  dashboardJailViewAllJailsRoute: dashboardJailViewAllJailsRoute,
  dashboardJailIndexRoute: dashboardJailIndexRoute,
}

const dashboardJailRouteRouteWithChildren =
  dashboardJailRouteRoute._addFileChildren(dashboardJailRouteRouteChildren)

interface dashboardOrganizationRouteRouteChildren {
  dashboardOrganizationCreateNewOrganizationRoute: typeof dashboardOrganizationCreateNewOrganizationRoute
  dashboardOrganizationViewAllOrganizationsRoute: typeof dashboardOrganizationViewAllOrganizationsRoute
  dashboardOrganizationIndexRoute: typeof dashboardOrganizationIndexRoute
}

const dashboardOrganizationRouteRouteChildren: dashboardOrganizationRouteRouteChildren =
  {
    dashboardOrganizationCreateNewOrganizationRoute:
      dashboardOrganizationCreateNewOrganizationRoute,
    dashboardOrganizationViewAllOrganizationsRoute:
      dashboardOrganizationViewAllOrganizationsRoute,
    dashboardOrganizationIndexRoute: dashboardOrganizationIndexRoute,
  }

const dashboardOrganizationRouteRouteWithChildren =
  dashboardOrganizationRouteRoute._addFileChildren(
    dashboardOrganizationRouteRouteChildren,
  )

interface dashboardTendersRouteRouteChildren {
  dashboardTendersCreateNewTenderRoute: typeof dashboardTendersCreateNewTenderRoute
  dashboardTendersViewTendersRoute: typeof dashboardTendersViewTendersRoute
  dashboardTendersIndexRoute: typeof dashboardTendersIndexRoute
  dashboardTendersTenderDetailsIdRoute: typeof dashboardTendersTenderDetailsIdRoute
  dashboardTendersTenderDetailsIdAddParticipantsRoute: typeof dashboardTendersTenderDetailsIdAddParticipantsRoute
}

const dashboardTendersRouteRouteChildren: dashboardTendersRouteRouteChildren = {
  dashboardTendersCreateNewTenderRoute: dashboardTendersCreateNewTenderRoute,
  dashboardTendersViewTendersRoute: dashboardTendersViewTendersRoute,
  dashboardTendersIndexRoute: dashboardTendersIndexRoute,
  dashboardTendersTenderDetailsIdRoute: dashboardTendersTenderDetailsIdRoute,
  dashboardTendersTenderDetailsIdAddParticipantsRoute:
    dashboardTendersTenderDetailsIdAddParticipantsRoute,
}

const dashboardTendersRouteRouteWithChildren =
  dashboardTendersRouteRoute._addFileChildren(
    dashboardTendersRouteRouteChildren,
  )

interface dashboardRouteRouteChildren {
  dashboardJailRouteRoute: typeof dashboardJailRouteRouteWithChildren
  dashboardOrganizationRouteRoute: typeof dashboardOrganizationRouteRouteWithChildren
  dashboardTendersRouteRoute: typeof dashboardTendersRouteRouteWithChildren
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardTenderParticipantParticipantIdRoute: typeof dashboardTenderParticipantParticipantIdRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardJailRouteRoute: dashboardJailRouteRouteWithChildren,
  dashboardOrganizationRouteRoute: dashboardOrganizationRouteRouteWithChildren,
  dashboardTendersRouteRoute: dashboardTendersRouteRouteWithChildren,
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardTenderParticipantParticipantIdRoute:
    dashboardTenderParticipantParticipantIdRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
