/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardJailRouteRouteImport } from './routes/(dashboard)/jail/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as dashboardJailIndexRouteImport } from './routes/(dashboard)/jail/index'
import { Route as dashboardJailCreateNewJailRouteImport } from './routes/(dashboard)/jail/create-new-jail'
import { Route as dashboardJailViewAllJailsRouteImport } from './routes/(dashboard)/jail/view-all-jails'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardJailRouteRoute = dashboardJailRouteRouteImport.update({
  id: '/jail',
  path: '/jail',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const dashboardJailIndexRoute = dashboardJailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardJailRouteRoute,
} as any)
const dashboardJailCreateNewJailRoute =
  dashboardJailCreateNewJailRouteImport.update({
    id: '/create-new-jail',
    path: '/create-new-jail',
    getParentRoute: () => dashboardJailRouteRoute,
  } as any)
const dashboardJailViewAllJailsRoute =
  dashboardJailViewAllJailsRouteImport.update({
    id: '/view-all-jails',
    path: '/view-all-jails',
    getParentRoute: () => dashboardJailRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/jail': typeof dashboardJailRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof dashboardIndexRoute
  '/jail/create-new-jail': typeof dashboardJailCreateNewJailRoute
  '/jail/view-all-jails': typeof dashboardJailViewAllJailsRoute
  '/jail/': typeof dashboardJailIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof dashboardIndexRoute
  '/jail/create-new-jail': typeof dashboardJailCreateNewJailRoute
  '/jail/view-all-jails': typeof dashboardJailViewAllJailsRoute
  '/jail': typeof dashboardJailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(dashboard)/jail': typeof dashboardJailRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/jail/create-new-jail': typeof dashboardJailCreateNewJailRoute
  '/(dashboard)/jail/view-all-jails': typeof dashboardJailViewAllJailsRoute
  '/(dashboard)/jail/': typeof dashboardJailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/jail'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/jail/create-new-jail'
    | '/jail/view-all-jails'
    | '/jail/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/jail/create-new-jail'
    | '/jail/view-all-jails'
    | '/jail'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/auth'
    | '/(dashboard)/jail'
    | '/auth/login'
    | '/auth/signup'
    | '/(dashboard)/'
    | '/(dashboard)/jail/create-new-jail'
    | '/(dashboard)/jail/view-all-jails'
    | '/(dashboard)/jail/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/jail': {
      id: '/(dashboard)/jail'
      path: '/jail'
      fullPath: '/jail'
      preLoaderRoute: typeof dashboardJailRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(dashboard)/jail/': {
      id: '/(dashboard)/jail/'
      path: '/'
      fullPath: '/jail/'
      preLoaderRoute: typeof dashboardJailIndexRouteImport
      parentRoute: typeof dashboardJailRouteRoute
    }
    '/(dashboard)/jail/create-new-jail': {
      id: '/(dashboard)/jail/create-new-jail'
      path: '/create-new-jail'
      fullPath: '/jail/create-new-jail'
      preLoaderRoute: typeof dashboardJailCreateNewJailRouteImport
      parentRoute: typeof dashboardJailRouteRoute
    }
    '/(dashboard)/jail/view-all-jails': {
      id: '/(dashboard)/jail/view-all-jails'
      path: '/view-all-jails'
      fullPath: '/jail/view-all-jails'
      preLoaderRoute: typeof dashboardJailViewAllJailsRouteImport
      parentRoute: typeof dashboardJailRouteRoute
    }
  }
}

interface dashboardJailRouteRouteChildren {
  dashboardJailCreateNewJailRoute: typeof dashboardJailCreateNewJailRoute
  dashboardJailViewAllJailsRoute: typeof dashboardJailViewAllJailsRoute
  dashboardJailIndexRoute: typeof dashboardJailIndexRoute
}

const dashboardJailRouteRouteChildren: dashboardJailRouteRouteChildren = {
  dashboardJailCreateNewJailRoute: dashboardJailCreateNewJailRoute,
  dashboardJailViewAllJailsRoute: dashboardJailViewAllJailsRoute,
  dashboardJailIndexRoute: dashboardJailIndexRoute,
}

const dashboardJailRouteRouteWithChildren =
  dashboardJailRouteRoute._addFileChildren(dashboardJailRouteRouteChildren)

interface dashboardRouteRouteChildren {
  dashboardJailRouteRoute: typeof dashboardJailRouteRouteWithChildren
  dashboardIndexRoute: typeof dashboardIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardJailRouteRoute: dashboardJailRouteRouteWithChildren,
  dashboardIndexRoute: dashboardIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
